name: ID-Organics
favicon: null
layout_spectrum: 0.004042676417157054
typography_spectrum: 0.8493836256675422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7308801477774978
  lightness: 0.34171766811050475
  saturation: 0.185135803418234
  rhythmicContrast: 0.06507980753667653
purpose: []
